[package]
name = "coreio"
version = "0.0.1"
authors = []


[dependencies.core]
git = "https://github.com/RustOS-Fork-Holding-Ground/rust"
branch = "rustos"

[dependencies.void]
git = "https://github.com/RustOS-Fork-Holding-Ground/rust-void"
branch = "rustos"
default-features = false
